name: Create Release and Tag
on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Create Release and Tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0
    - name: 'Get next minor version'
      id: minortag
      uses: WyriHaximus/github-action-next-semvers@v1
      with:
        version: ${{ steps.previoustag.outputs.tag }}
