# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Test for Continuous integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: ['22.x']
        mongodb-version: ['5.0']
    steps:
    - name: Start MongoDB  
      run: sudo docker run --name mongodb -d -p 27017:27017 mongo:${{ matrix.mongodb-version }}
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install taxi-back dependencies from package-lock.json
      run: pnpm i --force --frozen-lockfile
    - name: Run unit tests
      run: pnpm run test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DB_PATH: ${{ secrets.DB_PATH }}
        PORT: ${{ secrets.PORT }}
        SESSION_KEY: ${{ secrets.SESSION_KEY }}
